import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { inspectSchoolWorkbook } from './workbook.mjs';

const root = resolve(import.meta.dirname, '..', '..');
const workbookPath = join(root, 'data', 'import', 'schools', 'school_DATA.xlsx');
const reportPath = join(root, 'data', 'import', 'schools', 'import-report.json');
const normalizedPath = join(root, 'data', 'import', 'schools', 'normalized-schools.json');
const migrationPath = join(
  root,
  'supabase',
  'migrations',
  '20260902000400_real_school_dataset.sql',
);

function sqlLiteral(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

function renderMigration(schools, sourceSha256) {
  const values = schools
    .map(
      (school) =>
        `  (${[
          school.id,
          school.import_key,
          school.name,
          school.slug,
          school.type,
          school.city,
          school.county,
        ]
          .map(sqlLiteral)
          .join(', ')})`,
    )
    .join(',\n');

  return `-- Generated by npm run schools:generate. Do not edit school rows manually.
-- Source SHA-256: ${sourceSha256}

insert into public.schools (id, import_key, name, slug, type, city, county)
values
${values}
on conflict do nothing;
`;
}

const { schools, report } = inspectSchoolWorkbook(workbookPath);
const mode = process.argv[2] ?? '--validate';
const renderedReport = `${JSON.stringify(report, null, 2)}\n`;
const renderedSchools = `${JSON.stringify(schools, null, 2)}\n`;
const renderedMigration = renderMigration(schools, report.source.sha256);

if (report.source.sourceRows !== 2790) {
  throw new Error(`Váratlan forrássorszám: ${report.source.sourceRows}; elvárt: 2790`);
}
if (report.source.dataSheets !== 20 || report.source.inspectedSheets.length !== 21) {
  throw new Error('A munkafüzet munkalapkészlete megváltozott.');
}
if (report.countyMismatches.length > 0) {
  throw new Error(`Vármegye/munkalap eltérés: ${report.countyMismatches.length}`);
}
if (report.invalidRows.length !== 1) {
  throw new Error(`Váratlan érvénytelen sorszám: ${report.invalidRows.length}; elvárt: 1`);
}
if (report.exactDuplicateRowsRemoved !== 16 || report.finalSchoolCount !== 2773) {
  throw new Error(
    `Váratlan deduplikációs eredmény: ${report.exactDuplicateRowsRemoved} duplikátum, ${report.finalSchoolCount} iskola.`,
  );
}

if (mode === '--generate') {
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, renderedReport, 'utf8');
  writeFileSync(normalizedPath, renderedSchools, 'utf8');
  writeFileSync(migrationPath, renderedMigration, 'utf8');
  process.stdout.write(
    `Generated ${schools.length} normalized schools and an idempotent migration.\n`,
  );
} else if (mode === '--validate') {
  const generatedFiles = [
    [reportPath, renderedReport],
    [normalizedPath, renderedSchools],
    [migrationPath, renderedMigration],
  ];
  for (const [path, expected] of generatedFiles) {
    if (readFileSync(path, 'utf8') !== expected) {
      throw new Error(`Az importált fájl elavult: ${path}. Futtasd: npm run schools:generate`);
    }
  }
  process.stdout.write(
    `Validated ${report.source.sourceRows} rows across ${report.source.dataSheets} data sheets; ` +
      `${report.exactDuplicateRowsRemoved} exact duplicates collapsed; ${schools.length} schools ready.\n`,
  );
} else {
  throw new Error('Használat: node scripts/schools/import-schools.mjs --validate|--generate');
}
